### ISSUE TITLE
Symbian 9.x port

### ISSUE THREAD

**Issue by Symbian9** [warmplace/sunvox_dll#1]
Need any instruction how port it to Series S60 devices
* Forum - http://www.warmplace.ru/forum/viewtopic.php?t=3548

### TOOLS
Here are developper tools
* Symbian Dev Tools for Linux+Wine
  * https://cloud.mail.ru/public/JxE5/CDr4AStEZ
  * https://github.com/mstorsjo/gnupoc-package
  * https://github.com/Symbian9/GCCE4Symbian
* https://github.com/Symbian9/SymbianBook_ru

### REFERENCES
MOD library and player written with PyS60 and Symbian C
* https://code.google.com/archive/p/pys60modlib/
* https://code.google.com/archive/p/pymuz/

LCG Xplore filemanager sourcecode
* https://github.com/Symbian9/X-plore_free/
  * https://github.com/Symbian9/X-plore_free/blob/master/LibSrc/Symbian/SndPlayer.cpp

FFMPEG port for Symbian
* https://sourceforge.net/projects/ffmpegforsymbia/

OGG Vorbis codec port for Symbian
* https://sourceforge.net/projects/s60oggvorbiscodec/

OGG Vorbis player
* https://sourceforge.net/projects/symbianoggplay/

**Comment by gldnspud** [comment]
Hi @Symbian9 - NightRadio isn't active on GitHub right now. 

These are mirrors for the benefit and interest of the SunVox community; I've obtained permission from NightRadio to maintain them, but they shouldn't be considered a place to file requests or bug reports.

To avoid future confusion, I'll disable the GitHub issue tracker on these repos, and provide a link to the forums to obtain support.

As far as any specific ports, we'll have to let NightRadio decide whether or not to do this, and when will be good for his schedule.
